name: shiny-deploy

on:
  push:
    branches:
      - main

jobs:
  shiny-deploy:
    runs-on: ubuntu-latest
    env:
      # Note, this name is referred to in 'global.R'
      VENV_NAME: virtual_env
 
    steps:
 
      - uses: actions/checkout@v2
        
      - name: Install R packages
        run: |
          # The binary package distributions from R Studio dramatically speed up installation time
          options(repos = c(REPO_NAME = "https://packagemanager.rstudio.com/all/__linux__/focal/latest", 
             getOption("repos")))
          install.packages(c("shiny", "tidyverse", "DT"))
          reticulate::virtualenv_create(envname = 'python3_env')
          reticulate::virtualenv_install('python3_env', packages = c('requests', "pandas"))
        shell: Rscript {0}

      - name: Authorize and deploy app
        run: |
          branch<-Sys.getenv("GITHUB_REF_NAME")
          repo<-Sys.getenv("GITHUB_REPOSITORY")
          appName<-strsplit(repo, "/")[[1]][2]

          rsConnectUser <-"${{ secrets.RSCONNECT_USER }}"
          rsConnectToken <- "${{ secrets.RSCONNECT_TOKEN }}"
          rsConnectSecret <- "${{ secrets.RSCONNECT_SECRET }}"
 
          rsconnect::setAccountInfo(rsConnectUser, rsConnectToken, rsConnectSecret)
          rsconnect::deployApp(appName = appName)
        shell: Rscript {0}