name: shiny-deploy

on:
  push:
    branches:
      - main

jobs:
  shiny-deploy:
    runs-on: ubuntu-latest
    container: rocker/rstudio:4.2.2
    env:
       # This should not be necessary for installing from public repo's however install_github() fails without it.
      GITHUB_PAT: ${{ secrets.REPO_PAT }}
      
    steps:
    
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pip python3-venv libcurl4-openssl-dev
          
      - name: Create and Activate Python Virtual Environment
        shell: bash
        run: |
          python3 -m venv python3_env
          chmod 755 python3_env/bin/activate
          source python3_env/bin/activate
 
      - uses: actions/checkout@v2
        
      - name: Install R packages
        run: |
          options(repos = c(REPO_NAME = "https://packagemanager.rstudio.com/all/__linux__/focal/latest", getOption("repos")))
        
          install.packages(c("shiny", "DT", "reticulate", "rsconnect", "openssl"))
          library(reticulate)
          reticulate::virtualenv_install('python3_env', packages = c('requests', "pandas"))
          
        shell: Rscript {0}

      - name: Authorize and deploy app
        run: |
          repo<-Sys.getenv("GITHUB_REPOSITORY")
          appName<-strsplit(repo, "/")[[1]][2]
          appName = paste(appName, "", sep="")
        
          rsConnectUser <-"${{ secrets.RSCONNECT_USER }}"
          rsConnectToken <- "${{ secrets.RSCONNECT_TOKEN }}"
          rsConnectSecret <- "${{ secrets.RSCONNECT_SECRET }}"
 
          rsconnect::setAccountInfo(rsConnectUser, rsConnectToken, rsConnectSecret)
          rsconnect::deployApp(appName = appName, forceUpdate = TRUE)
        shell: Rscript {0}